# Generated by Django 6.0.8 on 2026-09-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ['-created_at'], 'verbose_name': 'Equipment Operator', 'verbose_name_plural': 'Equipment Operators'},
        ),
        migrations.AddField(
            model_name='operator',
            name='certification_type',
            field=models.CharField(blank=True, choices=[('EXCAVATOR', 'Hydraulic Excavator Operator'), ('BULLDOZER', 'Track-Type Tractor / Dozer Operator'), ('WHEEL_LOADER', 'Wheel Loader Operator'), ('DUMP_TRUCK', 'Articulated Dump Truck Operator'), ('MOTOR_GRADER', 'Motor Grader Operator'), ('COMPACTOR', 'Compactor Operator'), ('CRANE', 'Crane / Telehandler Operator'), ('GENERATOR', 'Generator Set Operator'), ('MULTI', 'Multi-Equipment Certified')], default='MULTI', help_text='Primary equipment category certification held by this operator', max_length=50),
        ),
        migrations.AddField(
            model_name='operator',
            name='license_expiry',
            field=models.DateField(blank=True, help_text='License expiry date — alerts triggered 30 days before expiry', null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='license_number',
            field=models.CharField(blank=True, help_text='Government-issued heavy machinery operating license number', max_length=100),
        ),
        migrations.AddField(
            model_name='operator',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='total_engine_hours_operated',
            field=models.FloatField(default=0.0, help_text='Cumulative engine hours operated across all Cat machines'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='employee_id',
            field=models.CharField(help_text='Caterpillar employee ID, e.g. CAT-OP-1001', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['certification_type'], name='operators_o_certifi_8fd80b_idx'),
        ),
    ]
