# Generated by Django 4.2.8 on 2026-09-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_equipment', models.IntegerField(default=0)),
                ('available_equipment', models.IntegerField(default=0)),
                ('rented_equipment', models.IntegerField(default=0)),
                ('in_use_equipment', models.IntegerField(default=0)),
                ('idle_equipment', models.IntegerField(default=0)),
                ('maintenance_equipment', models.IntegerField(default=0)),
                ('overdue_equipment', models.IntegerField(default=0)),
                ('offline_equipment', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tracking_dashboard_metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='tracking_da_timesta_a90f5d_idx')],
            },
        ),
    ]
