# Generated by Django 6.0.8 on 2026-09-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job Site', 'verbose_name_plural': 'Job Sites'},
        ),
        migrations.AddField(
            model_name='site',
            name='client_name',
            field=models.CharField(blank=True, help_text='Client or contractor organization name', max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='geofence_radius_meters',
            field=models.PositiveIntegerField(default=2000, help_text='Radius in meters defining the site geofence boundary'),
        ),
        migrations.AddField(
            model_name='site',
            name='project_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='project_manager',
            field=models.CharField(blank=True, help_text='Name of the Caterpillar project/site manager responsible', max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_type',
            field=models.CharField(choices=[('CONSTRUCTION', 'Construction Site'), ('MINING', 'Open-Cast Mining Site'), ('ROAD', 'Road / Highway Project'), ('TUNNEL', 'Tunneling / Underground Project'), ('MARINE', 'Marine / Port / Dredging Project'), ('QUARRY', 'Quarry / Aggregate Extraction'), ('DEPOT', 'Equipment Depot / Yard')], default='CONSTRUCTION', help_text='Nature of the project at this site', max_length=30),
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Site centroid latitude — used for geofence boundary calculations', null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Site centroid longitude — used for geofence boundary calculations', null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(help_text="Full project name, e.g. 'Bengaluru Metro Underground Line 4'", max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_code',
            field=models.CharField(help_text='Unique Caterpillar site code, e.g. S-CAT-BLR01', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('COMPLETED', 'Project Completed')], default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['site_type'], name='sites_site_site_ty_6e0946_idx'),
        ),
    ]
