# Generated by Django 4.2.8 on 2026-09-01 08:35

import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLiveState',
            fields=[
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='live_state', serialize=False, to='equipment.equipment')),
                ('status', models.CharField(default='OFFLINE', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True, validators=[common.validators.validate_latitude])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[common.validators.validate_longitude])),
                ('engine_hours', models.FloatField(blank=True, null=True)),
                ('idle_hours', models.FloatField(blank=True, null=True)),
                ('fuel_level', models.FloatField(blank=True, null=True, validators=[common.validators.validate_fuel_level])),
                ('speed', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_states', to='operators.operator')),
            ],
            options={
                'db_table': 'telemetry_equipment_live_state',
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('latitude', models.FloatField(validators=[common.validators.validate_latitude])),
                ('longitude', models.FloatField(validators=[common.validators.validate_longitude])),
                ('engine_hours', models.FloatField(validators=[common.validators.validate_non_negative])),
                ('idle_hours', models.FloatField(validators=[common.validators.validate_non_negative])),
                ('fuel_level', models.FloatField(validators=[common.validators.validate_fuel_level])),
                ('fuel_consumed', models.FloatField(default=0, validators=[common.validators.validate_non_negative])),
                ('speed', models.FloatField(default=0, validators=[common.validators.validate_speed_range])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telemetry', to='equipment.equipment')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry', to='operators.operator')),
            ],
            options={
                'db_table': 'telemetry_telemetry',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['equipment', 'timestamp'], name='telemetry_t_equipme_8fc2d2_idx'), models.Index(fields=['event_id'], name='telemetry_t_event_i_0685ea_idx'), models.Index(fields=['timestamp'], name='telemetry_t_timesta_e8cd0f_idx')],
            },
        ),
    ]
