# Generated by Django 4.2.8 on 2026-09-01 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=50, unique=True)),
                ('equipment_type', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('rfid_uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'Rented'), ('IN_USE', 'In Use'), ('IDLE', 'Idle'), ('MAINTENANCE', 'Maintenance'), ('OVERDUE', 'Overdue'), ('OFFLINE', 'Offline')], default='AVAILABLE', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='operators.operator')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='sites.site')),
            ],
            options={
                'db_table': 'equipment_equipment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['equipment_id'], name='equipment_e_equipme_0c3500_idx'), models.Index(fields=['status'], name='equipment_e_status_fb8540_idx'), models.Index(fields=['site'], name='equipment_e_site_id_febaef_idx'), models.Index(fields=['current_operator'], name='equipment_e_current_96556d_idx')],
            },
        ),
    ]
