# Generated by Django 6.0.8 on 2026-09-01 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('operators', '0002_alter_operator_options_operator_certification_type_and_more'),
        ('sites', '0002_alter_site_options_site_client_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Caterpillar Equipment', 'verbose_name_plural': 'Caterpillar Equipment Fleet'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='engine_model',
            field=models.CharField(blank=True, help_text="Cat engine model powering this machine, e.g. 'Cat C9.3B'", max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_maintenance_hours',
            field=models.FloatField(blank=True, help_text='Engine hours reading at last completed service', null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_interval_hours',
            field=models.PositiveIntegerField(default=500, help_text='Preventive maintenance interval in engine hours (default 500h)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacture_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year the machine was manufactured', null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal fleet notes'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rated_payload_tonnes',
            field=models.FloatField(blank=True, help_text='Rated payload capacity in metric tonnes (for trucks/loaders)', null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='telematics_device_id',
            field=models.CharField(blank=True, help_text='Cat Product Link / VisionLink device serial number', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='current_operator',
            field=models.ForeignKey(blank=True, help_text='Certified operator currently assigned to this machine', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='operators.operator'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_id',
            field=models.CharField(help_text='Unique CAT fleet asset ID, e.g. CAT-336-1001', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('EXCAVATOR', 'Hydraulic Excavator'), ('BULLDOZER', 'Track-Type Tractor / Bulldozer'), ('WHEEL_LOADER', 'Wheel Loader'), ('DUMP_TRUCK', 'Articulated / Off-Highway Dump Truck'), ('MOTOR_GRADER', 'Motor Grader'), ('COMPACTOR', 'Vibratory Soil / Asphalt Compactor'), ('CRANE', 'Telehandler / Rough Terrain Crane'), ('GENERATOR', 'Diesel Generator Set'), ('SKID_STEER', 'Skid Steer Loader'), ('BACKHOE', 'Backhoe Loader'), ('PIPELAYER', 'Pipelayer'), ('SCRAPER', 'Elevating / Push-Pull Scraper')], default='EXCAVATOR', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(default='Caterpillar Inc.', help_text="Always 'Caterpillar Inc.' for this system", max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, help_text="Full Cat model name, e.g. 'Cat 336 Heavy Excavator'", max_length=150),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='qr_code',
            field=models.CharField(blank=True, help_text='QR code sticker value for field scanning and checkout', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rfid_uid',
            field=models.CharField(blank=True, help_text='RFID tag UID attached to the machine frame', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Caterpillar PIN (Product Identification Number)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Current assigned construction/mining job site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'Rented'), ('IN_USE', 'In Use'), ('IDLE', 'Idle'), ('MAINTENANCE', 'Under Maintenance'), ('OVERDUE', 'Overdue - Not Returned'), ('OFFLINE', 'Offline / No Signal')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_type'], name='equipment_e_equipme_ce5345_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['telematics_device_id'], name='equipment_e_telemat_51cf70_idx'),
        ),
    ]
