# Generated by Django 4.2.8 on 2026-09-01 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_reference', models.CharField(max_length=50, unique=True)),
                ('checkout_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField()),
                ('checkin_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('CHECKED_OUT', 'Checked Out'), ('ACTIVE', 'Active'), ('CHECKED_IN', 'Checked In'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='equipment.equipment')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='operators.operator')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='sites.site')),
            ],
            options={
                'db_table': 'rentals_rental',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rental_reference'], name='rentals_ren_rental__f4967d_idx'), models.Index(fields=['equipment', 'status'], name='rentals_ren_equipme_da97ef_idx'), models.Index(fields=['operator'], name='rentals_ren_operato_3a81dd_idx'), models.Index(fields=['site'], name='rentals_ren_site_id_57ce4e_idx'), models.Index(fields=['status'], name='rentals_ren_status_fdfce4_idx'), models.Index(fields=['due_at'], name='rentals_ren_due_at_859aaa_idx')],
            },
        ),
    ]
