# Generated by Django 4.2.8 on 2026-09-01 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('current_utilization', models.FloatField()),
                ('predicted_target_demand', models.FloatField()),
                ('score', models.FloatField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('acted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='equipment.equipment')),
                ('source_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_recommendations', to='sites.site')),
                ('target_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_recommendations', to='sites.site')),
            ],
            options={
                'db_table': 'recommendations_recommendation',
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=100)),
                ('forecast_date', models.DateField()),
                ('predicted_demand', models.FloatField()),
                ('confidence', models.FloatField()),
                ('model_version', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='sites.site')),
            ],
            options={
                'db_table': 'forecasting_forecast',
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField()),
                ('anomaly_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('reason', models.TextField()),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='equipment.equipment')),
            ],
            options={
                'db_table': 'anomaly_detection_anomaly',
            },
        ),
    ]
